import { useEffect, useState } from 'react';
import { Bell, Box, Boxes, BookOpen, Check, ChevronDown, CircleHelp, Code2, Copy, FolderGit2, GitFork, Grid2X2, HardDrive, Image, LayoutDashboard, Menu, Package, Play, Plus, Search, Settings, ShieldCheck, Terminal, X, Zap } from 'lucide-react';

type Page = 'Dashboard' | 'API Docs' | 'Builds';
type Status = 'Success' | 'Building' | 'Failed' | 'Queued';
type RemoteBuild = {
  id: string;
  status: 'queued' | 'building' | 'success' | 'failed' | 'cancelled';
  repository: { owner: string; name: string };
  image: { reference: string; pullCommand: string };
};
const API_URL = import.meta.env.VITE_BUILD_API_URL ?? 'http://localhost:3001/api/builds';
const Github = GitFork;
const builds = [['kiran/example-app', 'a82df91', 'React', 'Success', '1m 14s', '2 min ago'], ['kiran/api-service', 'fa91be2', 'Node.js', 'Building', '—', '12 min ago'], ['kiran/python-api', 'ab72fd1', 'Python', 'Failed', '42s', '1 hour ago'], ['acme/design-system', '8cef120', 'Next.js', 'Queued', '—', '2 hours ago']] as const;
const nav: { name: Page; icon: typeof LayoutDashboard }[] = [{ name: 'Dashboard', icon: LayoutDashboard }, { name: 'API Docs', icon: BookOpen }];
const logs = ['$ git clone https://github.com/kiran/example-app', 'Cloning repository...', '✓ Repository cloned', 'Analyzing project...', '✓ Node.js detected', '✓ React + Vite detected', '✓ npm detected', '$ npm install', 'added 428 packages', '$ npm run build', 'vite building for production...', 'transforming modules...', '✓ 1287 modules transformed', 'dist/index.html', 'dist/assets/index.js', '✓ built successfully', 'Creating OCI image...', 'Exporting layers...', 'Pushing image...', 'Build completed successfully.'];
function Badge({ status }: { status: Status }) { return <span className={'badge ' + status.toLowerCase()}><i />{status}</span> }
function CopyButton({ value }: { value: string }) { const [done, setDone] = useState(false); return <button className="icon-btn" title="Copy command" onClick={() => { navigator.clipboard?.writeText(value); setDone(true); setTimeout(() => setDone(false), 1500) }}>{done ? <Check size={16} /> : <Copy size={16} />}</button> }
function App() {
    const [page, setPage] = useState<Page>('Dashboard'), [mobile, setMobile] = useState(false), [build, setBuild] = useState<'idle' | 'analyzing' | 'building' | 'success' | 'failed'>('idle'), [repo, setRepo] = useState('https://github.com/kiran/example-app'), [remoteBuild, setRemoteBuild] = useState<RemoteBuild | null>(null), [toast, setToast] = useState(''); const notify = (s: string) => { setToast(s); setTimeout(() => setToast(''), 2200) };
    useEffect(() => { if (!remoteBuild || !['queued', 'building'].includes(remoteBuild.status)) return; const timer = window.setInterval(async () => { try { const response = await fetch(`${API_URL}/${remoteBuild.id}`); if (!response.ok) throw new Error('Unable to update build status'); const next: RemoteBuild = await response.json(); setRemoteBuild(next); if (next.status === 'success') setBuild('success'); if (next.status === 'failed' || next.status === 'cancelled') setBuild('failed'); } catch (error) { notify(error instanceof Error ? error.message : 'Unable to update build status'); } }, 2500); return () => clearInterval(timer); }, [remoteBuild?.id, remoteBuild?.status]);
    const start = async () => { setBuild('analyzing'); try { const response = await fetch(API_URL, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ repoUrl: repo }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setRemoteBuild(result); setBuild('building'); notify('Remote ECR build started'); } catch (error) { setBuild('idle'); notify(error instanceof Error ? error.message : 'Build failed to start'); } };
    return <div className="app">{mobile && <div className="scrim" onClick={() => setMobile(false)} />}<aside className={mobile ? 'open' : ''}><div className="brand"><span><Zap size={19} /></span>ImageForge</div><div className="brand-subtitle">PUBLIC SOURCE BUILDER</div><nav>{nav.map(({ name, icon: Icon }) => <button key={name} onClick={() => { setPage(name); setBuild('idle'); setMobile(false) }} className={page === name ? 'active' : ''}><Icon size={18} />{name}</button>)}</nav><div className="side-bottom"><button onClick={() => setPage('API Docs')}><CircleHelp size={18} />Documentation</button><div className="privacy-note"><ShieldCheck size={17} /><span><b>Stateless by design</b>Your repository URL is used only for this build.</span></div></div></aside><main><header><button className="menu" onClick={() => setMobile(true)}><Menu size={20} /></button><div className="crumb">ImageForge <span>/</span> <b>{build !== 'idle' ? 'Build in progress' : page}</b></div><div className="top-actions"><span className="public-pill"><i />Public API</span><button className="icon-btn" title="GitHub"><Github size={18} /></button></div></header><section className="content">{page === 'Dashboard' && build === 'idle' && <Dashboard repo={repo} setRepo={setRepo} start={start} setPage={setPage} />} {build === 'analyzing' && <Analysis />}{build === 'building' && <Progress build={remoteBuild} />} {build === 'success' && <Success image={remoteBuild?.image} restart={start} notify={notify} />} {build === 'failed' && <BuildFailed restart={start} />} {page === 'API Docs' && <ApiDocs notify={notify} />}</section></main>{toast && <div className="toast"><Check size={17} />{toast}</div>}</div>
}
function Dashboard({ repo, setRepo, start, setPage }: { repo: string; setRepo: (s: string) => void; start: () => void; setPage: (p: Page) => void }) { return <><div className="hero"><span className="eyebrow"><Zap size={14} />SOURCE TO IMAGE</span><h1>Build container images<br />from source.</h1><p>Paste a GitHub repository and turn your source code into a ready-to-use OCI container image.</p><div className="repo-card"><label>GitHub repository</label><div className="repo-form"><Github size={20} /><input value={repo} onChange={e => setRepo(e.target.value)} aria-label="GitHub repository URL" /><button onClick={start}>Build Image <Play size={15} /></button></div><footer><span><Check size={14} />Public repositories can be analyzed instantly.</span><button><Github size={15} />Connect GitHub</button></footer></div></div><section className="section-head"><div><h2>Recent builds</h2><p>Track the latest image builds across your projects.</p></div><button className="text-btn" onClick={() => setPage('Builds')}>View all builds →</button></section><BuildTable rows={builds.slice(0, 3)} /></> }
function BuildTable({ rows }: { rows: readonly (readonly string[])[] }) { return <div className="table-wrap"><table><thead><tr><th>Repository</th><th>Commit</th><th>Stack</th><th>Status</th><th>Build time</th><th>Image</th><th>Created</th></tr></thead><tbody>{rows.map((r, i) => <tr key={r[0]}><td><span className="repo-name"><Box size={16} />{r[0]}</span></td><td><code>{r[1]}</code></td><td>{r[2]}</td><td><Badge status={r[3] as Status} /></td><td>{r[4]}</td><td className="muted">{i === 0 ? 'imageforge.dev/kiran/example-app:a82df91' : '—'}</td><td className="muted">{r[5]}</td></tr>)}</tbody></table></div> }
function Analysis() { return <div className="build-view"><span className="eyebrow">BUILD #24</span><h1>Analyzing repository<span className="dots">...</span></h1><p>We’re inspecting your source code and build configuration.</p><div className="analysis-card"><div className="skeleton title" /><div className="analysis-grid">{Array.from({ length: 8 }, (_, i) => <div key={i}><div className="skeleton label" /><div className="skeleton line" /></div>)}</div></div></div> }
function Progress({ build }: { build: RemoteBuild | null }) {
  const isQueued = build?.status === 'queued';
  const steps = ['Repository queued', 'Remote build started', 'Creating OCI image', 'Pushing image to ECR', 'Build complete'];
  const currentStep = isQueued ? 0 : 2;
  return <div className="build-view"><div className="build-top"><div><span className="eyebrow">{build?.repository.owner} / {build?.repository.name}</span><h1>Building image</h1><p>CodeBuild is building and pushing this image to Amazon ECR.</p></div><Badge status={isQueued ? "Queued" : "Building"} /></div><div className="build-grid"><section className="steps"><h3>Build progress</h3>{steps.map((step, index) => <div className={'step ' + (index < currentStep ? 'complete' : index === currentStep ? 'current' : '')} key={step}><span>{index < currentStep ? <Check size={14} /> : index === currentStep ? <i /> : index + 1}</span><div><b>{step}</b><small>{index < currentStep ? 'Completed' : index === currentStep ? 'In progress' : 'Waiting to start'}</small></div></div>)}</section><section className="terminal"><div className="terminal-head"><span><i /><i /><i /></span><b><Terminal size={14} />Remote build status</b></div><pre>{`Build ID: ${build?.id}\nStatus: ${build?.status}\n\nThe frontend checks the backend every 2.5 seconds.\nThe ECR image URI appears when the build succeeds.`}</pre><footer><span><i />Live polling</span></footer></section></div></div>
}
function BuildFailed({ restart }: { restart: () => void }) { return <div className="result"><h1>Build failed</h1><p>CodeBuild could not publish this image to ECR. Verify the CodeBuild project, IAM permissions, and ECR repository.</p><button onClick={restart}>Try again <Play size={14} /></button></div> }
function Success({ image: ecrImage, restart, notify }: { image?: RemoteBuild['image']; restart: () => void; notify: (s: string) => void }) { const image = ecrImage?.reference ?? 'ECR image unavailable', pull = ecrImage?.pullCommand ?? ''; return <div className="result"><div className="success-icon"><Check size={33} /></div><span className="eyebrow">ECR IMAGE READY</span><h1>Your image is ready</h1><p>Your repository was successfully converted into a container image.</p><div className="command-card"><label>Amazon ECR image URI</label><div><code>{image}</code><CopyButton value={image} /></div></div><div className="command-card"><label>Docker pull command</label><div><code>{pull}</code><CopyButton value={pull} /></div></div><div className="metadata">{[['Image format', 'OCI'], ['Registry', 'Amazon ECR'], ['Created', 'Just now']].map(x => <div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><div className="result-actions"><button className="secondary" onClick={() => notify('Image URL copied')}>Copy Image</button><button onClick={restart}>Build Again <Play size={14} /></button></div></div> }
function Projects() { return <PageHead title="Projects" text="Source repositories configured to build container images." action="New Project"><div className="toolbar"><Search size={18} /><input placeholder="Search projects" /><button>Latest activity <ChevronDown size={15} /></button></div><div className="cards">{[['example-app', 'React + Vite', 'Success'], ['api-service', 'Node.js + Express', 'Building'], ['payment-service', 'Python FastAPI', 'Success']].map((p, i) => <article className="project" key={p[0]}><div><span className="project-icon"><Github size={20} /></span><Badge status={p[2] as Status} /></div><h3>{p[0]}</h3><p>{p[1]}</p><hr /><small>Latest image</small><code>imageforge.dev/kiran/{p[0]}:{i ? 'latest' : 'a82df91'}</code><footer>Updated {i + 1}h ago <span>→</span></footer></article>)}</div></PageHead> }
function Builds() { return <PageHead title="Builds" text="Every build across your ImageForge workspace."><div className="filter"><button className="selected">All</button>{['Success', 'Building', 'Failed', 'Queued'].map(x => <button key={x}>{x}</button>)}<div><Search size={16} /><input placeholder="Search repository" /></div></div><BuildTable rows={builds} /></PageHead> }
function Images({ notify }: { notify: (s: string) => void }) { return <PageHead title="Container images" text="Manage images generated from your source repositories."><div className="image-list">{['example-app:a82df91', 'api-service:fa91be2', 'payment-service:latest'].map((x, i) => <article key={x}><span className="image-icon"><Image size={21} /></span><div><code>registry.imageforge.dev/kiran/{x}</code><p>{x.split(':')[0]} · {i ? 'linux/amd64 · 96 MB' : 'linux/amd64 · 182 MB'} · {i + 1} hours ago</p></div><CopyButton value={'docker pull registry.imageforge.dev/kiran/' + x} /><button className="secondary">View project</button></article>)}</div></PageHead> }
function Registry() { return <PageHead title="Container Registry" text="Your private registry for production-ready OCI images."><div className="registry-host"><div><span className="project-icon"><Package size={22} /></span><div><small>REGISTRY HOSTNAME</small><h2>registry.imageforge.dev</h2></div></div><CopyButton value="registry.imageforge.dev" /></div><div className="stat-grid">{[['Total images', '24', Image], ['Storage used', '1.8 GB', HardDrive], ['Image pulls', '1,284', Boxes], ['Projects', '8', Grid2X2]].map(([a, b, Icon]) => { const I = Icon as typeof Image; return <article key={a as string}><I size={19} /><span>{a as string}</span><b>{b as string}</b></article> })}</div><div className="usage-code"><label>GET STARTED</label><code>docker login registry.imageforge.dev<br />docker pull registry.imageforge.dev/kiran/example-app:latest</code></div></PageHead> }
function SettingsPage({ notify }: { notify: (s: string) => void }) { return <PageHead title="Settings" text="Manage your workspace preferences and integrations."><div className="settings">{[['General', 'Display name', 'Kiran Shah', 'Default branch', 'main'], ['Build defaults', 'Build timeout', '20 minutes', 'Default image tag', 'latest'], ['GitHub connection', 'GitHub account', 'kiran-shah', 'Connection', 'Connected']].map(s => <article key={s[0]}><h3>{s[0]}</h3><div><label>{s[1]}</label><input defaultValue={s[2]} /></div><div><label>{s[3]}</label><input defaultValue={s[4]} /></div><footer><button className="secondary" onClick={() => notify('Settings saved')}>Save changes</button></footer></article>)}</div></PageHead> }
function ApiDocs({ notify }: { notify: (s: string) => void }) { const endpoint = 'https://api.imageforge.dev/v1/builds'; const request = `POST ${endpoint}\nContent-Type: application/json\n\n{"repository":"https://github.com/user/repository","tag":"latest"}`; return <div className="api-docs"><span className="eyebrow"><Code2 size={14} />DEVELOPER DOCUMENTATION</span><h1>Build images with the public API</h1><p>Submit a public repository URL and receive an OCI image. This interface uses a dummy endpoint only—no request is actually sent.</p><div className="api-layout"><section><div className="api-section"><h3><span className="method">POST</span> Create a build</h3><code>{endpoint}</code><p>Create an image from a public GitHub repository. Builds are ephemeral; no client projects or source code are stored.</p><div className="code-block"><div><span>Example request</span><CopyButton value={request} /></div><pre>{request}</pre></div></div><div className="api-section"><h3>Example response</h3><div className="code-block"><pre>{`{\n  "buildId": "build_demo_24",\n  "status": "complete",\n  "image": "registry.imageforge.dev/user/repository:latest",\n  "pullCommand": "docker pull registry.imageforge.dev/user/repository:latest"\n}`}</pre></div></div></section><aside className="api-callout"><ShieldCheck size={22} /><h3>Privacy first</h3><p>ImageForge does not require accounts or retain a project list. You bring a URL, get an image, and stay in control.</p><button onClick={() => { navigator.clipboard?.writeText(endpoint); notify('Dummy API URL copied') }}>Copy dummy API URL <Copy size={15} /></button></aside></div></div> }
function PageHead({ title, text, action, children }: { title: string; text: string; action?: string; children: React.ReactNode }) { return <div className="page"><div className="page-title"><div><h1>{title}</h1><p>{text}</p></div>{action && <button><Plus size={16} />{action}</button>}</div>{children}</div> }; export default App;
